## Write a Numpy program to compute the multiplication of two given matrixes

In [2]:
import numpy as np
def mul(mat1,mat2):
    rm=mat1*mat2
    return rm


In [3]:
mat1=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
mat2=np.array([[4,2,6],
               [4,3,3],
               [1,2,5]])
print(mul(mat1,mat2))

[[ 4  4 18]
 [16 15 18]
 [ 7 16 45]]


## Write a NumPy program to compute the determinant of a given square array

In [4]:
def det(mat1):
    rd=np.linalg.det(mat1)
    return rd

In [8]:
mat3=np.array([[1,2],
               [3,4]])
print(format(det(mat3),".2f"))

-2.00


In [57]:
mat3=np.array([[1,2],
               [3,4]])
print(det(mat3))

-2.0000000000000004


## Write a NumPy program to compute the cross product of two given vectors

In [47]:
def cp(v1,v2):
    mat=np.vstack((v1,v2))
    rcp=np.linalg.det(mat)
    return rcp

In [48]:
v1=np.array([2,2])
v2=np.array([1,2])
print(cp(v1,v2))

2.0


## Write a NumPy program to compute the condition number of a given matrix

## Write a NumPy program to compute the inverse of a given matrix

In [10]:
def inv(mat):
    rinv=np.linalg.inv(mat)
    return rinv

In [11]:
rinv_=inv(mat3)
print(rinv_)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [32]:
h=mat3.dot(rinv_)
print(h) # If its results become identity matrix so it is the true inverse
h=np.round(h,decimals=4)
print(h)

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]
[[1. 0.]
 [0. 1.]]
